function Wells(double) {
    this.times = [];
    var test = false;
    if (double){
        for (var i =0;i < 60; i++){
            this.times.push(i*60);
        }
    }
    else{
        for (var i =0;i < 120; i++){
            this.times.push(i*30);
        }
    }
    if (test) {
        for (var i =0;i < 120; i+=5){
            this.times.push(i);
        }
    }
    console.log(this.times);
    
    this.pages = [];
    this.pages[0] = "In the middle years of the nineteenth century there first became abundant in this strange world of ours a class of men, men tending for the most part to become elderly, who are called, and who are very properly called, but who dislike extremely to be called--'Scientists.' They dislike that word so much that from the columns of Nature, which was from the first their distinctive and characteristic paper, it is";
    this.pages[1] = "as carefully excluded as if it were--that other word which is the basis of all really bad language in this country. But the Great Public and its Press know better, and 'Scientists' they are, and when they emerge to any sort of publicity, 'distinguished scientists' and 'eminent scientists' and 'well-known scientists' is the very least we call them. Certainly both Mr. Bensington and Professor Redwood quite merited";
    this.pages[2] = "any of these terms long before they came upon the marvellous discovery of which this story tells. Mr. Bensington was a Fellow of the Royal Society and a former president of the Chemical Society, and Professor Redwood was Professor of Physiology in the Bond Street College of the London University, and he had been grossly libelled by the anti-vivisectionists time after time. And they had led lives of academic distinction from their very earliest youth.";
    this.pages[3] = "They were of course quite undistinguished looking men, as indeed all true Scientists are. There is more personal distinction about the mildest-mannered actor alive than there is about the entire Royal Society. Mr. Bensington was short and very, very bald, and he stooped slightly; he wore gold-rimmed spectacles and cloth boots that were abundantly cut open because of his numerous corns, and Professor Redwood was entirely ordinary";
    this.pages[4] = "in his appearance. Until they happened upon the Food of the Gods (as I must insist upon calling it) they led lives of such eminent and studious obscurity that it is hard to find anything whatever to tell the reader about them. Mr. Bensington won his spurs (if one may use such an expression of a gentleman in boots of slashed cloth) by his splendid researches upon the More Toxic Alkaloids,";
    this.pages[5] ="and Professor Redwood rose to eminence--I do not clearly remember how he rose to eminence! I know he was very eminent, and that's all. Things of this sort grow. I fancy it was a voluminous work on Reaction Times with numerous plates of sphygmograph tracings (I write subject to correction) and an admirable new terminology, that did the thing for him.The general public saw little or nothing";
    this.pages[6] = "of either of these gentlemen. Sometimes at places like the Royal Institution and the Society of Arts it did in a sort of way see Mr. Bensington, or at least his blushing baldness and something of his collar and coat, and hear fragments of a lecture or paper that he imagined himself to be reading audibly; and once I remember--one midday in the vanished past--when the British Association was at Dover, coming on Section C or D, or some such letter,";
    this.pages[7] = "which had taken up its quarters in a public-house, and following two, serious-looking ladies with paper parcels, out of mere curiosity, through a door labelled 'Billiards' and 'Pool' into a scandalous darkness, broken only by a magic-lantern circle of Redwood's tracings.I watched the lantern slides come and go, and listened to a voice (I forget what it was saying) which I believe was the voice of Professor Redwood, and there was a sizzling from the lantern and another sound";
    this.pages[8] =  "that kept me there, still out of curiosity, until the lights were unexpectedly turned up. And then I perceived that this sound was the sound of the munching of buns and sandwiches and things that the assembled British Associates had come there to eat under cover of the magic-lantern darkness. And Redwood I remember went on talking all the time the lights were up and dabbing at the place where his diagram ought to have been visible on the screen--and so it was again";
    this.pages[9] = "so soon as the darkness was restored. I remember him then as a most ordinary, slightly nervous-looking dark man, with an air of being preoccupied with something else, and doing what he was doing just then under an unaccountable sense of duty.I heard Bensington also once--in the old days--at an educational conference in Bloomsbury. Like most eminent chemists and botanists, Mr. Bensington was very authoritative upon teaching";
    this.pages[10] = "--though I am certain he would have been scared out of his wits by an average Board School class in half-an-hour--and so far as I can remember now, he was propounding an improvement of Professor Armstrong's Heuristic method, whereby at the cost of three or four hundred pounds' worth of apparatus, a total neglect of all other studies and the undivided attention of a teacher of exceptional gifts, an average child might with a peculiar sort of thumby thoroughness";
    this.pages[11] = "learn in the course of ten or twelve years almost as much chemistry as one could get in one of those objectionable shilling text-books that were then so common....Quite ordinary persons you perceive, both of them, outside their science. Or if anything on the unpractical side of ordinary. And that you will find is the case with 'scientists' as a class all the world over. What there is great of them is an annoyance to their fellow scientists";
    this.pages[12] = "and a mystery to the general public, and what is not is evident.There is no doubt about what is not great, no race of men have such obvious littlenesses. They live in a narrow world so far as their human intercourse goes; their researches involve infinite attention and an almost monastic seclusion; and what is left over is not very much. To witness some queer, shy, misshapen, greyheaded,";
    this.pages[13] = "self-important, little discoverer of great discoveries, ridiculously adorned with the wide ribbon of some order of chivalry and holding a reception of his fellow-men, or to read the anguish of Nature at the 'neglect of science' when the angel of the birthday honours passes the Royal Society by, or to listen to one indefatigable lichenologist commenting on the work of another indefatigable lichenologist, such things";
    this.pages[14] = "force one to realise the unfaltering littleness of men.And withal the reef of Science that these little 'scientists' built and are yet building is so wonderful, so portentous, so full of mysterious half-shapen promises for the mighty future of man! They do not seem to realise the things they are doing! No doubt long ago even Mr. Bensington, when he chose this calling, when he";
    this.pages[15] = "consecrated his life to the alkaloids and their kindred compounds, had some inkling of the vision,--more than an inkling. Without some such inspiration, for such glories and positions only as a 'scientist' may expect, what young man would have given his life to such work, as young men do? No, they must have seen the glory, they must have had the vision, but so near that it has blinded them. The splendour has blinded them, mercifully,";
    this.pages[16] = "so that for the rest of their lives they can hold the lights of knowledge in comfort--that we may see!And perhaps it accounts for Redwood's touch of preoccupation, that--there can be no doubt of it now--he among his fellows was different, he was different inasmuch as something of the vision still lingered in his eyes.The Food of the Gods I call it,";
    this.pages[17] = "this substance that Mr. Bensington and Professor Redwood made between them; and having regard now to what it has already done and all that it is certainly going to do, there is surely no exaggeration in the name. So I shall continue to call it therefore throughout my story. But Mr. Bensington would no more have called it that in cold blood than he would have gone out from his flat in Sloane Street clad in regal scarlet and a wreath of laurel. The phrase was a mere first";
    this.pages[18] = "cry of astonishment from him. He called it the Food of the Gods, in his enthusiasm and for an hour or so at the most altogether. After that he decided he was being absurd. When he first thought of the thing he saw, as it were, a vista of enormous possibilities--literally enormous possibilities; but upon this dazzling vista, after one stare of amazement, he resolutely shut his eyes, even as a conscientious";
    this.pages[19] = "'scientist' should. After that, the Food of the Gods sounded blatant to the pitch of indecency. He was surprised he had used the expression. Yet for all that something of that clear-eyed moment hung about him and broke out ever and again....'Really, you know,' he said, rubbing his hands together and laughing nervously, 'it has more than a theoretical interest.";
    this.pages[20] = "'For example,' he confided, bringing his face close to the Professor's and dropping to an undertone, 'it would perhaps, if suitably handled, sell.... 'Precisely,' he said, walking away,--'as a Food. Or at least a food ingredient. 'Assuming of course that it is palatable. A thing we cannot know till we have prepared it.'He turned upon the hearthrug, and studied the carefully designed slits upon his cloth shoes.";
   
    this.pages[21] = "'Name?' he said, looking up in response to an inquiry. 'For my part I incline to the good old classical allusion. It--it makes Science res--. Gives it a touch of old-fashioned dignity. I have been thinking ... I don't know if you will think it absurd of me.... A little fancy is surely occasionally permissible.... Herakleophorbia. Eh? The nutrition of a possible Hercules? You know it might ...'Of course if you think not--'";
    this.pages[22] = "Redwood reflected with his eyes on the fire and made no objection.'You think it would do?' Redwood moved his head gravely. 'It might be Titanophorbia, you know. Food of Titans.... You prefer the former? 'You're quite sure you don't think it a little too--''No.''Ah! I'm glad.' And so they called it Herakleophorbia";
    this.pages[23] = "throughout their investigations, and in their report,--the report that was never published, because of the unexpected developments that upset all their arrangements,--it is invariably written in that way. There were three kindred substances prepared before they hit on the one their speculations had foretolds and these they spoke of as Herakleophorbia I, Herakleophorbia II, and Herakleophorbia III. It is Herakleophorbia IV.";
    this.pages[24] = "which I--insisting upon Bensington's original name--call here the Food of the Gods. The idea was Mr. Bensington's. But as it was suggested to him by one of Professor Redwood's contributions to the Philosophical Transactions, he very properly consulted that gentleman before he carried it further. Besides which it was, as a research,";
    this.pages[25] = "a physiological, quite as much as a chemical inquiry. Professor Redwood was one of those scientific men who are addicted to tracings and curves. You are familiar--if you are at all the sort of reader I like--with the sort of scientific paper I mean. It is a paper you cannot make head nor tail of, and at the end come five or six long folded diagrams that open out and show peculiar zigzag tracings, flashes";
    this.pages[26] = "of lightning overdone, or sinuous inexplicable things called 'smoothed curves' set up on ordinates and rooting in abscissae--and things like that. You puzzle over the thing for a long time and end with the suspicion that not only do you not understand it but that the author does not understand it either. But really you know many of these scientific people understand the meaning of their own papers quite well: it is simply";
    this.pages[27] = "a defect of expression that raises the obstacle between us. I am inclined to think that Redwood thought in tracings and curves. And after his monumental work upon Reaction Times (the unscientific reader is exhorted to stick to it for a little bit longer and everything will be as clear as daylight) Redwood began to turn out smoothed curves and sphygmographeries upon Growth, and it was one of his papers upon Growth that really gave";
    this.pages[28] = "Mr. Bensington his idea. Redwood, you know, had been measuring growing things of all sorts, kittens, puppies, sunflowers, mushrooms, bean plants, and (until his wife put a stop to it) his baby, and he showed that growth went out not at a regular pace, or, as he put it, so, but with bursts and intermissions of this sort.";
    this.pages[29] = "and that apparently nothing grew regularly and steadily, and so far as he could make out nothing could grow regularly and steadily: it was as if every living thing had just to accumulate force to grow, grew with vigour only for a time, and then had to wait for a space before it could go on growing again. And in the muffled and highly technical";
    this.pages[30] = "language of the really careful 'scientist,' Redwood suggested that the process of growth probably demanded the presence of a considerable quantity of some necessary substance in the blood that was only formed very slowly, and that when this substance was used up by growth, it was only very slowly replaced, and that meanwhile the organism had to mark time. He compared his unknown substance to oil in machinery. A growing animal was rather";
    this.pages[31] = "like an engine, he suggested, that can move a certain distance and must then be oiled before it can run again. ('But why shouldn't one oil the engine from without?' said Mr. Bensington, when he read the paper.) And all this, said Redwood, with the delightful nervous inconsecutiveness of his class, might very probably be found to throw a light upon the mystery of certain of the ductless glands. As though they had anything to do with it at all!";
    this.pages[32] = "In a subsequent communication Redwood went further. He gave a perfect Brock's benefit of diagrams--exactly like rocket trajectories they were; and the gist of it--so far as it had any gist--was that the blood of puppies and kittens and the sap of sunflowers and the juice of mushrooms in what he called the 'growing phase' differed in the proportion of certain elements from their blood and sap on the days when they were not particularly growing.";
    this.pages[33] = "And when Mr. Bensington, after holding the diagrams sideways and upside down, began to see what this difference was, a great amazement came upon him. Because, you see, the difference might probably be due to the presence of just the very substance he had recently been trying to isolate in his researches upon such alkaloids as are most stimulating to the nervous system. He put down Redwood's paper on the patent reading-desk that swung inconveniently";
    this.pages[34] = "from his arm-chair, took off his gold-rimmed spectacles, breathed on them and wiped them very carefully. 'By Jove!' said Mr. Bensington. Then replacing his spectacles again he turned to the patent reading-desk, which immediately, as his elbow came against its arm, gave a coquettish squeak and deposited the paper, with all its diagrams in a dispersed and crumpled state, on the floor.";
    this.pages[35] = "'By Jove!' said Mr. Bensington, straining his stomach over the armchair with a patient disregard of the habits of this convenience, and then, finding the pamphlet still out of reach, he went down on all fours in pursuit. It was on the floor that the idea of calling it the Food of the Gods came to him.... For you see, if he was right and Redwood was right, then by injecting or administering this new substance";
    this.pages[36] = "of his in food, he would do away with the 'resting phase,' and instead of growth going on in this fashion, it would (if you follow me) go thus--‘The night after his conversation with Redwood Mr. Bensington could scarcely";
    this.pages[37] = "sleep a wink. He did seem once to get into a sort of doze, but it was only for a moment, and then he dreamt he had dug a deep hole into the earth and poured in tons and tons of the Food of the Gods, and the earth was swelling and swelling, and all the boundaries of the countries were bursting, and the Royal Geographical Society was all at work like one great guild of tailors letting out the equator.... That of course was a ridiculous dream, but it shows the state";
    this.pages[38] = "of mental excitement into which Mr. Bensington got and the real value he attached to his idea, much better than any of the things he said or did when he was awake and on his guard. Or I should not have mentioned it, because as a general rule I do not think it is at all interesting for people to tell each other about their dreams. By a singular coincidence Redwood also had a dream that night, and his dream was this:";
    this.pages[39] = "-- It was a diagram done in fire upon a long scroll of the abyss. And he (Redwood) was standing on a planet before a sort of black platform lecturing about the new sort of growth that was now possible, to the More than Royal Institution of Primordial Forces--forces which had always previously, even in the growth of races, empires, planetary systems, and worlds,";
    this.pages[40] = "gone so:-- And even in some cases so:-- And he was explaining to them quite lucidly and convincingly that these slow, Book one  chapter two, sectinsons one through 3 of the food of the gods by HG wells";
    this.pages[41] = "Mr. Bensington proposed originally to try this stuff, so soon as he was really able to prepare it, upon tadpoles. One always does    try this sort of thing upon tadpoles to begin with;";
    this.pages[42] = "this being what tadpoles are for. And it was agreed that he should conduct the experiments and not Redwood, because Redwood's laboratory was occupied with the ballistic apparatus and animals necessary for an investigation into the Diurnal Variation in the Butting Frequency of the Young Bull Calf, an investigation that was yielding curves of an abnormal and very perplexing sort, and the presence of glass globes of tadpoles was extremely undesirable while this particular";
    this.pages[43] = "research was in progress. But when Mr. Bensington conveyed to his cousin Jane something of what he had in mind, she put a prompt veto upon the importation of any considerable number of tadpoles, or any such experimental creatures, into their flat. She had no objection whatever to his use of one of the rooms of the flat for the purposes of a non-explosive chemistry that, so far as she was concerned, came to nothing;";
    this.pages[44] = "she let him have a gas furnace and a sink and a dust-tight cupboard of refuge from the weekly storm of cleaning she would not forego. And having known people addicted to drink, she regarded his solicitude for distinction in learned societies as an excellent substitute for the coarser form of depravity. But any sort of living things in quantity, 'wriggly' as they were bound to be alive and 'smelly' dead, she could not and would not abide.";
    this.pages[45] = "She said these things were certain to be unhealthy, and Bensington was notoriously a delicate man--it was nonsense to say he wasn't. And when Bensington tried to make the enormous importance of this possible discovery clear, she said that it was all very well, but if she consented to his making everything nasty and unwholesome in the place (and that was what it all came to) then she was certain he would be the first to complain. And Mr. Bensington";
    this.pages[46] = "went up and down the room, regardless of his corns, and spoke to her quite firmly and angrily without the slightest effect. He said that nothing ought to stand in the way of the Advancement of Science, and she said that the Advancement of Science was one thing and having a lot of tadpoles in a flat was another; he said that in Germany it was an ascertained fact that a man with an idea like his would at once have twenty thousand properly-fitted cubic feet";
    this.pages[47] = "of laboratory placed at his disposal, and she said she was glad and always had been glad that she was not a German; he said that it would make him famous for ever, and she said it was much more likely to make him ill to have a lot of tadpoles in a flat like theirs; he said he was master in his own house, and she said that rather than wait on a lot of tadpoles she'd go as matron to a school; and then he asked her to be reasonable, and she asked him";
    this.pages[48] = " to be reasonable then and give up all this about tadpoles; and he said she might respect his ideas, and she said not if they were smelly she wouldn't, and then he gave way completely and said--in spite of the classical remarks of Huxley upon the subject--a bad word. Not a very bad word it was, but bad enough. And after that she was greatly offended and had to be apologised to, and the prospect of";
    this.pages[49] = "ever trying the Food of the Gods upon tadpoles in their flat at any rate vanished completely in the apology. So Bensington had to consider some other way of carrying out these experiments in feeding that would be necessary to demonstrate his discovery, so soon as he had his substance isolated and prepared. For some days he meditated upon the possibility of boarding out his tadpoles with some trustworthy person, and then the chance sight";
    this.pages[50] = "of the phrase in a newspaper turned his thoughts to an Experimental Farm. And chicks. Directly he thought of it, he thought of it as a poultry farm. He was suddenly taken with a vision of wildly growing chicks. He conceived a picture of coops and runs, outsize and still more outsize coops, and runs progressively larger. Chicks are so accessible, so easily fed and observed, so much drier to handle and measure,";
    this.pages[51] = "that for his purpose tadpoles seemed to him now, in comparison with them, quite wild and uncontrollable beasts. He was quite puzzled to understand why he had not thought of chicks instead of tadpoles from the beginning. Among other things it would have saved all this trouble with his cousin Jane. And when he suggested this to Redwood, Redwood quite agreed with him.Redwood said that in working so much upon needlessly small animals";
    this.pages[52] = "he was convinced experimental physiologists made a great mistake. It is exactly like making experiments in chemistry with an insufficient quantity of material; errors of observation and manipulation become disproportionately large. It was of extreme importance just at present that scientific men should assert their right to have their material big. That was why he was doing his present series of experiments at the Bond Street College";
    this.pages[53] = "upon Bull Calves, in spite of a certain amount of inconvenience to the students and professors of other subjects caused by their incidental levity in the corridors. But the curves he was getting were quite exceptionally interesting, and would, when published, amply justify his choice. For his own part, were it not for the inadequate endowment of science in this country, he would never, if he could avoid it, work on anything smaller than a whale. But a Public";
    this.pages[54] = "Vivarium on a sufficient scale to render this possible was, he feared, at present, in this country at any rate, a Utopian demand. In Germany--Etc. As Redwood's Bull calves needed his daily attention, the selection and equipment of the Experimental Farm fell largely on Bensington. The entire cost also, was, it was understood, to be defrayed by Bensington, at least until a grant could be obtained. Accordingly";
    this.pages[55] = "he alternated his work in the laboratory of his flat with farm hunting up and down the lines that run southward out of London, and his peering spectacles, his simple baldness, and his lacerated cloth shoes filled the owners of numerous undesirable properties with vain hopes. And he advertised in several daily papers and Nature for a responsible couple (married), punctual, active, and used to poultry, to take entire charge of an Experimental Farm of three acres.";
    this.pages[56] = "He found the place he seemed in need of at Hickleybrow, near Urshot, in Kent. It was a little queer isolated place, in a dell surrounded by old pine woods that were black and forbidding at night. A humped shoulder of down cut it off from the sunset, and a gaunt well with a shattered penthouse dwarfed the dwelling. The little house was creeperless, several windows were broken, and the cart shed had a black shadow";
    this.pages[57] = "at midday. It was a mile and a half from the end house of the village, and its loneliness was very doubtfully relieved by an ambiguous family of echoes. The place impressed Bensington as being eminently adapted to the requirements of scientific research. He walked over the premises sketching out coops and runs with a sweeping arm, and he found the kitchen capable of accommodating a series of incubators and foster mothers with the very minimum of alteration.";
    this.pages[58] = "He took the place there and then; on his way back to London he stopped at Dunton Green and closed with an eligible couple that had answered his advertisements, and that same evening he succeeded in isolating a sufficient quantity of Herakleophorbia I. to more than justify these engagements. The eligible couple who were destined under Mr. Bensington to be the first almoners on earth of the Food of the Gods, were not only very perceptibly aged,";
    this.pages[59] = "but also extremely dirty. This latter point Mr. Bensington did not observe, because nothing destroys the powers of general observation quite so much as a life of experimental science. They were named Skinner, Mr. and Mrs. Skinner, and Mr. Bensington interviewed them in a small room with hermetically sealed windows, a spotted overmantel looking-glass, and some ailing calceolarias. Mrs. Skinner was a very little old woman, capless,";
    this.pages[60] = "with dirty white hair drawn back very very tightly from a face that had begun by being chiefly, and was now, through the loss of teeth and chin, and the wrinkling up of everything else, ending by being almost exclusively--nose. She was dressed in slate colour (so far as her dress had any colour) slashed in one place with red flannel. She let him in and talked to him guardedly and peered at him round and over her nose, while Mr. Skinner she alleged";
    this.pages[61] = "made some alteration in his toilette. She had one tooth that got into her articulations and she held her two long wrinkled hands nervously together. She told Mr. Bensington that she had managed fowls for years; and knew all about incubators; in fact, they themselves had run a Poultry Farm at one time, and it had only failed at last through the want of pupils. 'It's the pupils as pay,' said Mrs. Skinner.";
    this.pages[62] = "Mr. Skinner, when he appeared, was a large-faced man, with a lisp and a squint that made him look over the top of your head, slashed slippers that appealed to Mr. Bensington's sympathies, and a manifest shortness of buttons. He held his coat and shirt together with one hand and traced patterns on the black-and-gold tablecloth with the index finger of the other, while his disengaged eye watched Mr. Bensington's sword of Damocles, so to speak,";
    this.pages[63] = "with an expression of sad detachment. 'You don't want to run thith Farm for profit. No, Thir. Ith all the thame, Thir. Ekthperimenth! Prethithely.' He said they could go to the farm at once. He was doing nothing at Dunton Green except a little tailoring. 'It ithn't the thmart plathe I thought it wath, and what I get ithent thkarthely worth having,' he said, 'tho that if it ith any convenienth to you for uth to come....'";
    this.pages[64] = "And in a week Mr. and Mrs. Skinner were installed in the farm, and the jobbing carpenter from Hickleybrow was diversifying the task of erecting runs and henhouses with a systematic discussion of Mr. Bensington. 'I haven't theen much of 'im yet,' said Mr. Skinner. 'But as far as I can make 'im out 'e theems to be a thtewpid o' fool.' 'I thought 'e seemed a bit Dotty,'";
    this.pages[65] = "said the carpenter from Hickleybrow. ''E fanthieth 'imself about poultry,' said Mr. Skinner. 'O my goodneth! You'd think nobody knew nothin' about poultry thept 'im.'''E looks like a 'en,' said the carpenter from Hickleybrow; 'what with them spectacles of 'is.' Mr. Skinner came closer to the carpenter from Hickleybrow, and spoke in a confidential manner, and one sad eye regarded the distant village,";
    this.pages[66] = "and one was bright and wicked. 'Got to be meathured every blethed day--every blethed 'en, 'e thays. Tho as to thee they grow properly. What oh ... eh? Every blethed 'en--every blethed day.' And Mr. Skinner put up his hand to laugh behind it in a refined and contagious manner, and humped his shoulders very much--and only the other eye of him failed to participate in his laughter. Then doubting";
    this.pages[67] = "if the carpenter had quite got the point of it, he repeated in a penetrating whisper; 'Meathured!'''E's worse than our old guvnor; I'm dratted if 'e ain't,' said the carpenter from Hickleybrow. Experimental work is the most tedious thing in the world (unless it be the reports of it in the Philosophical Transactions), and it seemed a long time to Mr. Bensington";
    this.pages[68] = "before his first dream of enormous possibilities was replaced by a crumb of realisation. He had taken the Experimental Farm in October, and it was May before the first inklings of success began. Herakleophorbia I. and II. and III. had to be tried, and failed; there was trouble with the rats of the Experimental Farm, and there was trouble with the Skinners. The only way to get Skinner to do anything he was told to do was to dismiss him.";
    this.pages[69] = "Then he would nib his unshaven chin--he was always unshaven most miraculously and yet never bearded--with a flattened hand, and look at Mr. Bensington with one eye, and over him with the other, and say, 'Oo, of courthe, Thir--if you're theriouth!' But at last success dawned. And its herald was a letter in the long slender handwriting of Mr. Skinner.'The new";
    this.pages[70] = "Brood are out,' wrote Mr. Skinner, 'and don't quite like the look of them. Growing very rank--quite unlike what the similar lot was before your last directions was given. The last, before the cat got them, was a very nice, stocky chick, but these are Growing like thistles. I never saw. They peck so hard, striking above boot top, that am unable to give exact Measures as requested. They are regular Giants,";
    this.pages[71] = "and eating as such. We shall want more com very soon, for you never saw such chicks to eat. Bigger than Bantams. Going on at this rate, they ought to be a bird for show, rank as they are. Plymouth Rocks won't be in it. Had a scare last night thinking that cat was at them, and when I looked out at the window could have sworn I see her getting in under the wire. The chicks was all awake and pecking about hungry when I went out, but could not see anything of the cat.";
    this.pages[72] = "So gave them a peck of corn, and fastened up safe. Shall be glad to know if the Feeding to be continued as directed. Food you mixed is pretty near all gone, and do not like to mix any more myself on account of the accident with the pudding. With best wishes from us both, and soliciting continuance of esteemed favours,'Respectfully yours,'ALFRED NEWTON SKINNER.' The allusion towards the end referred to a milk pudding with which some Herakleophorbia II.";
    this.pages[73] = "had got itself mixed with painful and very nearly fatal results to the Skinners. But Mr. Bensington, reading between the lines saw in this rankness of growth the attainment of his long sought goal. The next morning he alighted at Urshot station, and in the bag in his hand he carried, sealed in three tins, a supply of the Food of the Gods sufficient for all the chicks in Kent.It was a bright and beautiful morning";
    this.pages[74] = "late in May, and his corns were so much better that he resolved to walk through Hickleybrow to his farm. It was three miles and a half altogether, through the park and villages and then along the green glades of the Hickleybrow preserves. The trees were all dusted with the green spangles of high spring, the hedges were full of stitchwort and campion and the woods of blue hyacinths and purple orchid; and everywhere there was a great noise of birds--";
    this.pages[75] = "thrushes, blackbirds, robins, finches, and many more--and in one warm corner of the park some bracken was unrolling, and there was a leaping and rushing of fallow deer. These things brought back to Mr. Bensington his early and forgotten delight in life; before him the promise of his discovery grew bright and joyful, and it seemed to him that indeed he must have come upon the happiest day in his life. And when in the sunlit run by the sandy bank";
    this.pages[76] = "under the shadow of the pine trees he saw the chicks that had eaten the food he had mixed for them, gigantic and gawky, bigger already than many a hen that is married and settleds and still growing, still in their first soft yellow plumage (just faintly marked with brown along the back), he knew indeed that his happiest day had come.At Mr. Skinner's urgency he went into the runs but after he had been pecked through the cracks in his shoes";
    this.pages[77] = "once or twice he got out again, and watched these monsters through the wire netting. He peered close to the netting, and followed their movements as though he had never seen a chick before in his life.'Whath they'll be when they're grown up ith impothible to think,' said Mr. Skinner. 'Big as a horse,' said Mr. Bensington.'Pretty near,' said Mr. Skinner.'Several people could dine off a wing!'";
    this.pages[78] = "said Mr. Bensington. 'They'd cut up into joints like butcher's meat.''They won't go on growing at thith pathe though,' said Mr. Skinner. 'No?' said Mr. Bensington.'No,' said Mr. Skinner. 'I know thith thort. They begin rank, but they don't go on, bleth you! No.'There was a pause.'Itth management,' said Mr. Skinner modestly.";
    this.pages[79] = "Mr. Bensington turned his glasses on him suddenly. 'We got 'em almoth ath big at the other plathe,' said Mr. Skinner, with his better eye piously uplifted and letting himself go a little; 'me and the mithith.' Mr. Bensington made his usual general inspection of the premises, but he speedily returned to the new run. It was, you know, in truth ever so much more than he had dared to expect.";
    this.pages[80] = "The course of science is so tortuous and so slow; after the clear promises and before the practical realisation arrives there comes almost always year after year of intricate contrivance, and here--here was the Foods of the Gods arriving after less than a year of testing! It seemed too good--too good. That Hope Deferred which is the daily food of the scientific imagination was to be his no more!";
    this.pages[81] = "So at least it seemed to him then. He came back and stared at these stupendous chicks of his, time after time. 'Let me see,' he said. 'They're ten days old. And by the side of an ordinary chick I should fancy--about six or seven times as big....' 'Itth about time we artht for a rithe in thkrew,' said Mr. Skinner to his wife. 'He'th ath pleathed ath Punth";
    this.pages[82] = "about the way we got thothe chickth on in the further run--pleathed ath Punth he ith.' He bent confidentially towards her. 'Thinkth it'th that old food of hith,' he said behind his hands and made a noise of suppressed laughter in his pharyngeal cavity.... Mr. Bensington was indeed a happy man that day. He was in no mood to find fault with details of management. The bright day certainly brought out";
    this.pages[83] = "the accumulating slovenliness of the Skinner couple more vividly than he had ever seen it before. But his comments were of the gentlest. The fencing of many of the runs was out of order, but he seemed to consider it quite satisfactory when Mr. Skinner explained that it was a 'fokth or a dog or thomething' did it. He pointed out that the incubator had not been cleaned. 'That it asn't, Sir,' said Mrs. Skinner";
    this.pages[84] = "with her arms folded, smiling coyly behind her nose. 'We don't seem to have had time to clean it not since we been 'ere....' He went upstairs to see some rat-holes that Skinner said would justify a trap--they certainly were enormous--and discovered that the room in which the Food of the Gods was mixed with meal and bran was in a quite disgraceful order. The Skinners were the sort of people who find a use for cracked saucers";
    this.pages[85] = "and old cans and pickle jars and mustard boxes, and the place was littered with these. In one corner a great pile of apples that Skinner had saved was decaying, and from a nail in the sloping part of the ceiling hung several rabbit skins, upon which he proposed to test his gift as a furrier. ('There ithn't mutth about furth and thingth that I don't know,' said Skinner.) Mr. Bensington certainly sniffed";
    this.pages[86] = "critically at this disorder, but he made no unnecessary fuss, and even when he found a wasp regaling itself in a gallipot half full of Herakleophorbia IV, he simply remarked mildly that his substance was better sealed from the damp than exposed to the air in that manner. And he turned from these things at once to remark--what had been for some time in his mind--'I think, Skinner--you know, I shall kill one of these chicks--";
    this.pages[87] = "as a specimen. I think we will kill it this afternoon, and I will take it back with me to London.' He pretended to peer into another gallipot and then took off his spectacles to wipe them. ;’I should like,' he said, 'I should like very much, to have some relic--some memento--of this particular brood at this particular day.' 'By-the-bye,' he said, 'you don't give those little chicks meat?''Oh! no, Thir,'";
    this.pages[88] = "said Skinner, 'I can athure you, Thir, we know far too much about the management of fowlth of all dethcriptionth to do anything of that thort.''Quite sure you don't throw your dinner refuse--I thought I noticed the bones of a rabbit scattered about the far corner of the run--' But when they came to look at them they found they were the larger bones of a cat picked very clean and dry.";
    this.pages[89] = "'That's no chick,' said Mr. Bensington's cousin Jane. 'Well, I should think I knew a chick when I saw it,' said Mr. Bensington's cousin Jane hotly. 'It's too big for a chick, for one thing, and besides you can see perfectly well it isn't a chick.'It's more like a bustard than a chick.' 'For my part,' said Redwood, reluctantly allowing Bensington";
    this.pages[90] = "to drag him into the argument, 'I must confess that, considering all the evidence--' 'Oh I if you do that,' said Mr. Bensington's cousin Jane, 'instead of using your eyes like a sensible person--''Well, but really, Miss Bensington--!' 'Oh! Go on!' said Cousin Jane. 'You men are all alike.' 'Considering all the evidence, this certainly falls within the definition";
    this.pages[91] = "--no doubt it's abnormal and hypertrophied, but still--especially since it was hatched from the egg of a normal hen--Yes, I think, Miss Bensington, I must admit--this, so far as one can call it anything, is a sort of chick.''You mean it's a chick?' said cousin Jane. 'I think it's a chick,' said Redwood.'What NONSENSE!' said Mr. Bensington's cousin Jane, and 'Oh!'";
    this.pages[92] = "directed at Redwood's head, 'I haven't patience with you,' and then suddenly she turned about and went out of the room with a slam. 'And it's a very great relief for me to see it too, Bensington,' said Redwood, when the reverberation of the slam had died away. 'In spite of its being so big.' Without any urgency from Mr. Bensington he sat down in the low arm-chair by the fire and confessed";
    this.pages[93] = "to proceedings that even in an unscientific man would have been indiscreet. 'You will think it very rash of me, Bensington, I know,' he said, 'but the fact is I put a little--not very much of it--but some--into Baby's bottle, very nearly a week ago!' 'But suppose--!' cried Mr. Bensington.'I know,' said Redwood, and glanced at the giant chick upon the plate on the table.";
    this.pages[94] = "'It's turned out all right, thank goodness,' and he felt in his pocket for his cigarettes. He gave fragmentary details. 'Poor little chap wasn't putting on weight... desperately anxious.--Winkles, a frightful duffer ... former pupil of mine ... no good.... Mrs. Redwood--unmitigated confidence in Winkles.... You know, man with a manner like a cliff--towering.... No confidence in me, of course.... Taught Winkles....";
    this.pages[95] = "Scarcely allowed in the nursery.... Something had to be done.... Slipped in while the nurse was at breakfast ... got at the bottle.' 'But he'll grow,' said Mr. Bensington. 'He's growing. Twenty-seven ounces last week.... You should hear Winkles. It's management, he said.' 'Dear me! That's what Skinner says!' Redwood looked at the chick again. 'The bother is to keep it up,' he said.";
    this.pages[96] = "'They won't trust me in the nursery alone, because I tried to get a growth curve out of Georgina Phyllis--you know--and how I'm to give him a second dose--' 'Need you?' 'He's been crying two days--can't get on with his ordinary food again, anyhow. He wants some more now.' 'Tell Winkles.' 'Hang Winkles!' said Redwood. 'You might get at Winkles and give him powders to give the child--' 'That's about what I shall have to do,'";
    this.pages[97] = "said Redwood, resting his chin on his fist and staring into the fire. Bensington stood for a space smoothing the down on the breast of the giant chick. 'They will be monstrous fowls,' he said. 'They will,' said Redwood, still with his eyes on the glow. 'Big as horses,' said Bensington. 'Bigger,' said Redwood. 'That's just it!’ Bensington";
    this.pages[98] = "turned away from the specimen. 'Redwood,' he said, 'these fowls are going to create a sensation.' Redwood nodded his head at the fire. 'And by Jove!' said Bensington, coming round suddenly with a flash in his spectacles, 'so will your little boy!' 'That's just what I'm thinking of,' said Redwood. He sat back, sighed, threw his unconsumed cigarette into the fire and thrust his";
    this.pages[99] = "hands deep into his trousers pockets. 'That's precisely what I'm thinking of. This Herakleophorbia is going to be queer stuff to handle. The pace that chick must have grown at--!' 'A little boy growing at that pace,' said Mr. Bensington slowly, and stared at the chick as he spoke. 'I Say!' said Bensington, 'he'll be Big.' 'I shall give him diminishing doses,' said Redwood.";
    this.pages[100] = "'Or at any rate Winkles will.' 'It's rather too much of an experiment.' 'Much.' 'Yet still, you know, I must confess--... Some baby will sooner or later have to try it.' 'Oh, we'll try it on some baby--certainly.' 'Exactly so,' said Bensington, and came and stood on the hearthrug and took off his spectacles to wipe them.";
    this.pages[101] = "'Until I saw these chicks, Redwood, I don't think I began to realise--anything--of the possibilities of what we were making. It's only beginning to dawn upon me ... the possible consequences....' And even then, you know, Mr. Bensington was far from any conception of the mine that little train would fire. IV. That happened early in June. For some weeks Bensington was kept from revisiting the Experimental Farm";
    this.pages[102] = "by a severe imaginary catarrh, and one necessary flying visit was made by Redwood. He returned an even more anxious-looking parent than he had gone. Altogether there were seven weeks of steady, uninterrupted growth.... And then the Wasps began their career. It was late in July and nearly a week before the hens escaped from Hickleybrow that the first of the big wasps was killed. The report of it appeared";
    this.pages[103] = "in several papers, but I do not know whether the news reached Mr. Bensington, much less whether he connected it with the general laxity of method that prevailed in the Experimental Farm. There can be but little doubt now, that while Mr. Skinner was plying Mr. Bensington's chicks with Herakleophorbia IV, a number of wasps were just as industriously--perhaps more industriously--carrying quantities of the same paste to their early summer broods in the sand-banks";
    this.pages[104] = "beyond the adjacent pine-woods. And there can be no dispute whatever that these early broods found just as much growth and benefit in the substance as Mr. Bensington's hens. It is in the nature of the wasp to attain to effective maturity before the domestic fowl--and in fact of all the creatures that were--through the generous carelessness of the Skinners--partaking of the benefits Mr. Bensington heaped upon his hens, the wasps were the first";
    this.pages[105] = "to make any sort of figure in the world. It was a keeper named Godfrey, on the estate of Lieutenant-Colonel Rupert Hick, near Maidstone, who encountered and had the luck to kill the first of these monsters of whom history has any record. He was walking knee high in bracken across an open space in the beechwoods that diversify Lieutenant-Colonel Hick's park, and he was carrying his gun--very fortunately for him a double-barrelled gun--over his shoulder,";
    this.pages[106] = "when he first caught sight of the thing. It was, he says, coming down against the light, so that he could not see it very distinctly, and as it came it made a drone 'like a motor car.' He admits he was frightened. It was evidently as big or bigger than a barn owl, and, to his practised eye, its flight and particularly the misty whirl of its wings must have seemed weirdly unbirdlike. The instinct of self-defence, I fancy,";
    this.pages[107] = "mingled with long habit, when, as he says, he 'let fly, right away.' The queerness of the experience probably affected his aim; at any rate most of his shot missed, and the thing merely dropped for a moment with an angry 'Wuzzzz' that revealed the wasp at once, and then rose again, with all its stripes shining against the light. He says it turned on him. At any rate, he fired his second barrel at less than twenty yards";
    this.pages[108] = "and threw down his gun, ran a pace or so, and ducked to avoid it. It flew, he is convinced, within a yard of him, struck the ground, rose again, came down again perhaps thirty yards away, and rolled over with its body wriggling and its sting stabbing out and back in its last agony. He emptied both barrels into it again before he ventured to go near. When he came to measure the thing, he found it was twenty-seven";
    this.pages[109] = "and a half inches across its open wings, and its sting was three inches long. The abdomen was blown clean off from its body, but he estimated the length of the creature from head to sting as eighteen inches--which is very nearly correct. Its compound eyes were the size of penny pieces. That is the first authenticated appearance of these giant wasps. The day after, a cyclist riding, feet up,";
    this.pages[110] = "down the hill between Sevenoaks and Tonbridge, very narrowly missed running over a second of these giants that was crawling across the roadway. His passage seemed to alarm it, and it rose with a noise like a sawmill. His bicycle jumped the footpath in the emotion of the moment, and when he could look back, the wasp was soaring away above the woods towards Westerham. After riding unsteadily for a little time, he put on his brake, dismounted--he was trembling";
    this.pages[111] = "so violently that he fell over his machine in doing so--and sat down by the roadside to recover. He had intended to ride to Ashford, but he did not get beyond Tonbridge that day.... After that, curiously enough, there is no record of any big wasps being seen for three days. I find on consulting the meteorological record of those days that they were overcast and chilly with local showers, which may perhaps account for this intermission.";
    this.pages[112] = "Then on the fourth day came blue sky and brilliant sunshine and such an outburst of wasps as the world had surely never seen before. How many big wasps came out that day it is impossible to guess. There are at least fifty accounts of their apparition. There was one victim, a grocer, who discovered one of these monsters in a sugar-cask and very rashly attacked it with a spade as it rose. He struck it to the ground";
    this.pages[113] = "for a moment, and it stung him through the boot as he struck at it again and cut its body in half. He was first dead of the two.... The most dramatic of the fifty appearances was certainly that of the wasp that visited the British Museum about midday, dropping out of the blue serene upon one of the innumerable pigeons that feed in the courtyard of that building, and flying up to the cornice to devour its victim at leisure. After that it crawled";
    this.pages[114] = "for a time over the museum roof, entered the dome of the reading-room by a skylight, buzzed about inside it for some little time--there was a stampede among the readers--and at last found another window and vanished again with a sudden silence from human observation. Most of the other reports were of mere passings or descents. A picnic party was dispersed at Aldington Knoll and all its sweets and jam consumed, and a puppy was killed and torn to pieces near";
    this.pages[115] = "Whitstable under the very eyes of its mistress.... The streets that evening resounded with the cry, the newspaper placards gave themselves up exclusively in the biggest of letters to the 'Gigantic Wasps in Kent.' Agitated editors and assistant editors ran up and down tortuous staircases bawling things about 'wasps.' And Professor Redwood, emerging from his college in Bond Street at five, flushed from a heated discussion with his committee";
    this.pages[116] = "about the price of bull calves, bought an evening paper, opened it, changed colour, forgot about bull calves and committee forthwith, and took a hansom headlong for Bensington's flat. V. The flat was occupied, it seemed to him--to the exclusion of all other sensible objects--by Mr. Skinner and his voice, if indeed you can call either him or it a sensible object! The voice";
    this.pages[117] = "was up very high slopping about among the notes of anguish. 'Itth impothible for uth to thtop, Thir. We've thtopped on hoping thingth would get better and they've only got worth, Thir. It ithn't on'y the waptheth, Thir--thereth big earwigth, Thir--big ath that, Thir.' (He indicated all his hand and about three inches of fat dirty wrist.) 'They pretty near give Mithith Thkinner fitth, Thir. And the thtinging nettleth by the runth,";
    this.pages[118] = "Thir, they're growing, Thir, and the canary creeper, Thir, what we thowed near the think, Thir--it put itth tendril through the window in the night, Thir, and very nearly caught Mithith Thkinner by the legth, Thir. Itth that food of yourth, Thir. Wherever we thplathed it about, Thir, a bit, it'th thet everything growing ranker, Thir, than I ever thought anything could grow. Itth impothible to thtop a month, Thir. Itth more than our liveth are worth, Thir.";
    this.pages[119] = "Even if the waptheth don't thting uth, we thall be thuffocated by the creeper, Thir. You can't imagine, Thir--unleth you come down to thee, Thir--' He turned his superior eye to the cornice above Redwood's head. ''Ow do we know the ratth 'aven't got it, Thir! That 'th what I think of motht, Thir. I 'aven't theen any big ratth, Thir, but 'ow do I know, Thir. We been frightened for dayth becauth of the earwigth we've theen--";
    this.pages[120] = "";
    
    this.getWellsPage = function(start, end, maxChars) {
        var ret = book.slice(start, end);
        var chars = 0;

        for (var i in ret) {
            chars += ret[i].length;
            if (chars > maxChars) {
                end = i;
                break;
            }
        }
        return ret.slice(0, end);
    }
}
